# Generated by Django 3.2.5 on 2022-04-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_userreadinglist_date_read'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookorder',
            name='books',
        ),
        migrations.AddField(
            model_name='bookorder',
            name='books',
            field=models.ManyToManyField(to='books.Books'),
        ),
    ]
