# Generated by Django 3.2.5 on 2022-04-11 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20220411_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='start writing')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.books')),
            ],
        ),
    ]
