# Generated by Django 3.2.5 on 2022-04-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
