# Generated by Django 3.2.5 on 2022-04-11 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_userreadinglist_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreadinglist',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books'),
        ),
    ]
