# Generated by Django 3.2.5 on 2022-04-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_userlibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='books.Genre'),
        ),
    ]
