# Generated by Django 3.2.5 on 2022-04-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_like_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='write down the price of the book', max_digits=19),
        ),
    ]
