# Generated by Django 3.2.5 on 2022-04-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='status',
            field=models.CharField(default='publish', max_length=20),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
