# Generated by Django 3.2.5 on 2022-04-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_userbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(default='un-publish', max_length=20),
        ),
    ]
