# Generated by Django 3.2.5 on 2022-05-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_alter_books_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontent',
            name='content',
            field=models.TextField(default='', help_text='start writing'),
        ),
    ]
