# Generated by Django 3.2.5 on 2022-05-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_alter_bookcontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='write down the price of the book', max_digits=19),
        ),
    ]
