# Generated by Django 3.2.5 on 2022-05-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_alter_books_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='content_type',
            field=models.CharField(default='write', help_text='choose between write or pdf file', max_length=255),
        ),
    ]
