# Generated by Django 3.2.5 on 2022-05-15 04:43

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_alter_books_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontent',
            name='pdf',
            field=models.FileField(default=None, null=True, upload_to=books.models.upload_to),
        ),
        migrations.AlterField(
            model_name='books',
            name='content_type',
            field=models.CharField(blank=True, help_text='choose between write or pdf file', max_length=255, null=True),
        ),
    ]
