# Generated by Django 3.2.5 on 2022-03-29 02:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_myuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(default='images/users/profile/default/profile.jpg', upload_to=accounts.models.save_to),
        ),
    ]
