# Generated by Django 3.2.5 on 2022-04-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_myuser_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
