# Generated by Django 3.2.5 on 2022-04-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userlibrary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_email_verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_phone_verified',
        ),
    ]
