# Generated by Django 3.2.5 on 2022-04-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20220419_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='followers',
            field=models.BigIntegerField(default=0),
        ),
    ]
