# Generated by Django 3.2.5 on 2022-04-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_userlibrary_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLibrary',
        ),
    ]
