# Generated by Django 3.2.5 on 2022-04-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_delete_userlibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='my_books',
            field=models.IntegerField(default=0),
        ),
    ]
