# Generated by Django 3.2.5 on 2022-05-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='about_me',
            field=models.CharField(default='Hi, nice to meet you, hope you enjoy reading on Hasken Arewa', max_length=300),
        ),
    ]
